---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pesonaas/sa-badmintonapp.com/
    - git config core.fileMode false
    - /bin/mkdir -p $DEPLOYPATH/storage/framework/sessions $DEPLOYPATH/storage/framework/views $DEPLOYPATH/storage/framework/cache/data $DEPLOYPATH/storage/logs $DEPLOYPATH/bootstrap/cache
    - /bin/chmod -R 775 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache

